name: Deploy CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    
    - name: 安装 pnpm 环境
      uses: pnpm/action-setup@v2.0.1
      with:
        version: 7.29.1
          
    - name: 设置 Node.js ${{ matrix.node-version }} 环境
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
        
    - run: pnpm install
    - run: npm run build
    
#     - name: 自动同步文件夹到我的服务器
#       uses: wangyucode/sftp-upload-action@v1.1
#       with:
#         host: ${{ secrets.SERVER_IP }}  # nginx服务器公网ip
#         port: ${{ secrets.SERVER_PORT }} # nginx服务器ssh端口
#         username: ${{ secrets.USERNAME }} # nginx服务器用户名
#         password: ${{ secrets.PASSWORD }} # nginx服务器密码
#         localDir: "dist" # build好的文件的路径,每次服务器上会自动删除对应的文件夹后重新覆盖
#         remoteDir: ${{ secrets.SERVER_DESTINATION }} # 要把build好的文件夹放到nginx服务器上的什么位置
    
